import type { Metadata } from "next";
import "./globals.css";
import '@smastrom/react-rating/style.css'

export const metadata: Metadata = {
  title: "Team - Professional Marketing",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
